name: Foo the Bar

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.check.outputs.status }}
    
    steps:
    - uses: actions/checkout@master
      id: checkout
    
    - run: ./check.sh; echo "::set-output name=status::$?"
      shell: bash {0}
      id: check

  real1:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status == 0
    
    steps:
    - run: echo "status is zero"
      id: echo
  
  real2:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status != 0
    
    steps:
    - run: echo "status is not zero"
      id: echo
