name: Foo the Bar

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.check.outputs.status }}
      output: ${{ steps.check.outputs.output }}
    
    steps:
    - uses: actions/checkout@master
      id: checkout
    
    - run: |
        out=$(./check.sh)
        echo "::set-output name=status::$?"
        echo "::set-output name=output::${out}"

      shell: bash {0}
      id: check

  real1:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status == 0
    
    steps:
    - run: echo "status is zero, output is ${{needs.check.outputs.output}}"
      id: echo
  
  real2:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status != 0
    
    steps:
    - run: echo "status is not zero"
      id: echo
