name: Nightly Releases Checker

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      name: checkout
    
    - name: nightly-check
      id: check
      shell: bash {0}
      run: |
        ver=$(./check.sh)
        echo "::set-output name=status::$?"
        echo "::set-output name=version::${ver}"

    - name: create-release
      id: create
      if: steps.check.outputs.status == 0
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-${{ steps.check.outputs.version }}
        release_name: Nightly build from ${{ steps.check.outputs.version }}
        prerelease: true
        commitish: ${{ env.GITHUB_SHA }}
  
