name: Nightly Releases Builder

on:
  release:
    types:
      - created

jobs:
  build-docker:
  
    needs: check
    if: startsWith(github.event.release.name, 'nightly-')
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      name: checkout

    - name: nightly-check
      id: check
      shell: bash {0}
      run: |
        echo 'hello world' > build.txt

    - name: Upload Build
      id: upload-w32
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build.txt
        asset_name: build.txt
        asset_content_type: text/plain
